plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\Health Calculator\\fitmetrics-expo\\portfolio-site"
publishOrigin = "config"
commandOrigin = "ui"
base = "E:\\Health Calculator\\fitmetrics-expo\\portfolio-site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]